### ISSUE TITLE
Status naming mismatch?

### ISSUE THREAD

**Issue by Peter200lx** [hugapi/HOPE#12]
In https://github.com/hugapi/HOPE/blob/master/all/HOPE-0--HOPE-index.md#hope-status-key the possible Status's are enumerated as:
## HOPE Status Key

- *A* - Accepted (Standards Track only) or Active proposal
- *D* - Deferred proposal
- *F* - Final proposal
- *P* - Provisional proposal
- *R* - Rejected proposal
- *S* - Superseded proposal
- *W* - Withdrawn proposal

However in https://github.com/hugapi/HOPE/blob/master/all/HOPE-1--HOPE-Purpose-and-Guidelines.md#submitting-a-hope the only called out status is:
- `for the "Status:" field enter "Draft".`

Could we add clarity to HOPE 1 about the appropriate status at different stages of the process and make sure the status's fit with HOPE 0's key?

**Comment by timothycrosley** [comment]
I've done my best to clarify my understanding of the difference here: 
https://github.com/hugapi/HOPE#hope-status-key

and within HOPE1:
https://github.com/hugapi/HOPE/blob/master/all/HOPE-1--HOPE-Purpose-and-Guidelines.md#submitting-a-hope
```
If the HOPE isn't ready for approval, an editor will send it back to the author for revision, with specific instructions. Once approved, your HOPE will be assigned a unique number, added to the index, and given an appropriate status, generally opening it up for further review.
```

Note that these statuses come directly from Python's Enhancement Proposal structure, which also lists a Draft status in PEP1 but not in the index in PEP0. My understanding is this is simply because the PEP can't be in the index before it has made it past Draft status.
